from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.units import inch
from datetime import datetime
import os


def generate_evidence_pdf(
    case_id: str,
    victim: str,
    predator: str,
    incidents: list,
    output_path: str,
    pocso_applicable: bool = False,
) -> str:
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        "Title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#1a237e"), spaceAfter=6,
    )
    story.append(Paragraph("CYBERSHIELD AI — EVIDENCE REPORT", title_style))
    story.append(Paragraph("Generated in compliance with IT Act 2000 | Indian Evidence Act 1872", styles["Normal"]))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor("#1a237e")))
    story.append(Spacer(1, 12))

    metadata = [
        ["Case ID", case_id],
        ["Generated", datetime.now().strftime("%d %B %Y, %H:%M:%S IST")],
        ["Victim (Pseudonymized)", victim],
        ["Accused (Pseudonymized)", predator],
        ["Total Incidents", str(len(incidents))],
        ["POCSO Applicable", "YES — Minor involved" if pocso_applicable else "No"],
    ]
    meta_table = Table(metadata, colWidths=[2.5 * inch, 4 * inch])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#e8eaf6")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 16))

    story.append(Paragraph("APPLICABLE LEGAL PROVISIONS", styles["Heading2"]))
    legal = [
        "• IT Act 2000 — Section 66A: Offensive messages through communication service",
        "• IT Act 2000 — Section 67: Publishing obscene content in electronic form",
        "• IT Act 2000 — Section 67A: Sexually explicit content online",
        "• IPC Section 354D: Cyber stalking",
        "• IPC Section 499: Defamation",
        "• IPC Section 503: Criminal intimidation",
        "• IPC Section 507: Criminal intimidation by anonymous communication",
    ]
    if pocso_applicable:
        legal.append("• POCSO Act 2012 — Section 11: Sexual harassment of a child")
    for item in legal:
        story.append(Paragraph(item, styles["Normal"]))
    story.append(Spacer(1, 16))

    story.append(Paragraph("FLAGGED INCIDENTS", styles["Heading2"]))
    headers = ["#", "Timestamp", "Category", "Score", "Action", "Content (truncated)"]
    rows = [headers]
    for i, inc in enumerate(incidents, 1):
        content = inc.get("content", "")
        content = (content[:60] + "...") if len(content) > 60 else content
        rows.append([
            str(i),
            str(inc.get("timestamp", ""))[:19],
            inc.get("category", ""),
            f"{inc.get('harm_score', 0):.2f}",
            inc.get("action", "").upper(),
            content,
        ])
    inc_table = Table(rows, colWidths=[0.3 * inch, 1.2 * inch, 1.0 * inch, 0.5 * inch, 0.6 * inch, 2.9 * inch])
    inc_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a237e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.grey),
    ]))
    story.append(inc_table)
    story.append(Spacer(1, 20))

    story.append(Paragraph("HOW TO FILE A COMPLAINT", styles["Heading2"]))
    for line in [
        "1. Visit: https://cybercrime.gov.in",
        "2. Helpline: 1930 (Cyber Crime Helpline — 24/7)",
        "3. Women: NCW Helpline 7827170170 | ncw.nic.in",
        "4. For minors (POCSO): CHILDLINE 1098 | NCPCR ncpcr.gov.in",
        "5. Legal aid (free): NALSA 15100 | nalsa.gov.in",
    ]:
        story.append(Paragraph(line, styles["Normal"]))

    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        f"Auto-generated by CyberShield AI | Case ID: {case_id} | Do not alter | For cyber crime authorities only",
        ParagraphStyle("Footer", parent=styles["Normal"], fontSize=7, textColor=colors.grey),
    ))

    doc.build(story)
    return output_path
